# Generated by Django 5.2.6 on 2025-10-13 23:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area_trabajador', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('contrato_por_obra', 'Contrato por obra o faena'), ('contrato_plazo_fijo', 'Contrato a plazo fijo'), ('contrato_part_time', 'Contrato part time'), ('contrato_indefinido', 'Contrato indefinido'), ('contrato_para_extranjeros', 'Contrato para extranjeros')], default='contrato_indefinido', max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_marca', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('tolerancia_minutos', models.PositiveIntegerField(default=0, help_text='Minutos de tolerancia para atrasos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='login.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.turno'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('trabajador', 'Trabajador'), ('asistente_rrhh', 'Asistente RRHH'), ('admin_rrhh', 'Admin RRHH'), ('fiscalizador', 'Fiscalizador')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('trabajador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.trabajador')),
            ],
        ),
    ]
