# Generated by Django 5.2.6 on 2025-12-06 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('trabajador', 'Trabajador'), ('asistente_rrhh', 'Asistente RRHH'), ('admin_rrhh', 'Admin RRHH'), ('fiscalizador', 'Fiscalizador')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_empresa', to='login.empresa')),
            ],
            options={
                'verbose_name': 'Empresa de Usuario',
                'verbose_name_plural': 'Empresas de Usuario',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area_trabajador', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('contrato_por_obra', 'Contrato por obra o faena'), ('contrato_plazo_fijo', 'Contrato a plazo fijo'), ('contrato_part_time', 'Contrato part time'), ('contrato_indefinido', 'Contrato indefinido'), ('contrato_para_extranjeros', 'Contrato para extranjeros')], default='contrato_indefinido', max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_marca', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash', models.CharField(editable=False, max_length=64)),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('tolerancia_minutos', models.PositiveIntegerField(default=0, help_text='Minutos de tolerancia para atrasos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='login.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.turno'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.CharField(choices=[('trabajador', 'Trabajador'), ('asistente_rrhh', 'Asistente RRHH'), ('admin_rrhh', 'Admin RRHH'), ('fiscalizador', 'Fiscalizador')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresas_asignadas', models.ManyToManyField(blank=True, help_text='Empresas a las que este usuario puede acceder', related_name='usuarios_asignados', through='login.EmpresaUsuario', to='login.empresa')),
                ('trabajador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licencia_medica', 'Licencia medica'), ('permiso_administrativo', 'Permiso administrativo'), ('permiso_sin_goce', 'Permiso sin goce de sueldo')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(blank=True, help_text='Se calcula automaticamente si no se entrega', null=True)),
                ('motivo_detallado', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='licencias_pdfs/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencias', to='login.trabajador')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creo la licencia (normalmente el trabajador)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licencias_creadas', to='login.usuario')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licencias_resueltas', to='login.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empresausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_usuario', to='login.usuario'),
        ),
        migrations.CreateModel(
            name='AuditoriaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('registro_id', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='login.empresa')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizo la accion', on_delete=django.db.models.deletion.PROTECT, related_name='acciones_auditoria', to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones_creadas', to='login.usuario')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones_resueltas', to='login.usuario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones', to='login.trabajador')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='empresausuario',
            unique_together={('usuario', 'empresa')},
        ),
    ]
