# Generated by Django 5.2.6 on 2025-11-11 04:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('modelo_afectado', models.CharField(max_length=100)),
                ('registro_id', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la acción', on_delete=django.db.models.deletion.PROTECT, related_name='acciones_auditoria', to='login.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licencia_medica', 'Licencia médica'), ('permiso_administrativo', 'Permiso administrativo'), ('permiso_sin_goce', 'Permiso sin goce de sueldo')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField()),
                ('motivo_detallado', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencias_creadas', to='login.usuario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licencias', to='login.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.usuario')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones', to='login.trabajador')),
            ],
        ),
    ]
