# Generated by Django 5.2.6 on 2025-11-17 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_marcas_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
