# Generated by Django 5.2.6 on 2025-11-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_marcas_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='hash',
            field=models.CharField(default=0, editable=False, max_length=64),
            preserve_default=False,
        ),
    ]
