# Generated by Django 5.2.6 on 2025-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_marcas_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
