# Generated by Django 5.2.6 on 2025-11-18 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_licencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='licencias_pdfs/'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó la licencia (normalmente el trabajador)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licencias_creadas', to='login.usuario'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='dias',
            field=models.PositiveIntegerField(blank=True, help_text='Se calcula automáticamente si no se entrega', null=True),
        ),
    ]
