# Generated by Django 5.2.6 on 2025-11-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_licencia_archivo_alter_licencia_creado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacaciones',
            name='aprobado_por',
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones_creadas', to='login.usuario'),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacaciones',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones_resueltas', to='login.usuario'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
